## Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#version: 2.1
## Use a package of configuration called an orb.
#orbs:
#  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
## Orchestrate or schedule a set of jobs
#workflows:
#  # Name the workflow "welcome"
# # welcome:
#    # Run the welcome/run job in its own container
#    jobs:
#      - welcome/run
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:14.15.5-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
            cd client/
            pwd
      - run:
          name: Running in a Unique Container
          command: |
            node -v
            echo "The pwd is $PWD"
      

  test:
    docker: 
      - image: circleci/node:14.15.5-browsers
    steps:
      - checkout
      
      - run:
          name: Running custom tests
          command: |
            cd ./client
            echo "The pwd is $PWD"
            npm ci
            npm test
      - run:
            name: other tests
            background: true
            command: |
             cd ./server/TDD-Assignment/__tests__
             npm ci
             npm start
      
      - run:
            mocha ./server/TDD-Assignment/__tests__/server.test.js
            



orbs: 
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - build
      - test